version: "2"
services:
    notairesga-web:
        build: .
        restart: always
        ports:
            - "1045:8080"
        volumes:
            - ./uploads:/usr/src/app/cms1/public/uploads
        links:
            - notairesgastore
    notairesgastore:
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
